/// <reference path='../bower_components/DefinitelyTyped/angularjs/angular.d.ts' />
/// <reference path='../bower_components/DefinitelyTyped/angularjs/angular-resource.d.ts' />
/// <reference path='../bower_components/DefinitelyTyped/requirejs/require.d.ts' />
/// <reference path='../bower_components/DefinitelyTyped/angularfire/angularfire.d.ts'/>
/// <reference path='../app/config.ts' />
/// <reference path='../app/common/model/TargetGroup.ts' />
/// <reference path='../app/common/model/Category.ts' />
/// <reference path='../app/common/model/Article.ts' />
/// <reference path='../app/common/service/ShopService.ts' />
/// <reference path='../app/social/SocialController.ts' />
//# sourceMappingURL=_all.js.map