info:
    build:
        artifact: ${project.artifactId}
        name: ${project.name}
        description: ${project.description}
        version: ${project.version}
        buildTime: ${maven.build.timestamp}
ehcache:
    resourceFileName: ehcache.xml