FROM  docker-registry2.hackweek.aws.zalando/zalando-java:8u25-1

ADD target/social-shopping-webapp-1.0-SNAPSHOT.war /social-shopping-webapp-1.0-SNAPSHOT.war

CMD java -jar /social-shopping-webapp-1.0-SNAPSHOT.war
