FROM docker-registry.hackweek.aws.zalando/tsarnowski/zalando-java:8u25-1

ADD target/social-shopping-1.0-SNAPSHOT.jar /social-shopping-1.0-SNAPSHOT.jar

CMD java -jar /social-shopping-1.0-SNAPSHOT.jar
